apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autotls-webhook.fullname" . }}
  labels:
    {{- include "autotls-webhook.labels" . | nindent 4 }}
data:
  ingressDomain: {{ .Values.ingressDomain }}
  clusterIssuer: {{ .Values.clusterIssuer }}
